# httpOnly: if true then browser script won't be able to access the cookie
# secure: if true then the cookie will be sent only over HTTPS connection
server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      timeout: 15m
      cookie:
        http-only: true
        secure: false
      security:
        cors-origin: ${SERVER_CORS:http://localhost:3000}
      max-session-number: 5

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # see: https://jdbc.postgresql.org/documentation/ssl/
  datasource.url: ${PG_URL:jdbc:postgresql://localhost:5432}/${PG_DB:cfis}?ApplicationName=cfis&ssl=true&sslmode=disable&client_encoding=UTF8
  datasource.driver-class-name: org.postgresql.Driver
  datasource.username: ${PG_USR:cfis_user}
  datasource.password: ${PG_PWD:cfis_password}

  liquibase:
    enabled: ${LB_EBD:true}
    drop-first: ${LB_DF:true}
    change-log: classpath:category_file_info_service_changelog.xml
    default-schema: ${PG_SHM:public}

logging:
  level:
    root: ${LOGGING_LEVEL:DEBUG}
    org.numamo: ${LOGGING_LEVEL:DEBUG}
    org.springframework: ${LOGGING_LEVEL:DEBUG}
    org.hibernate: ${LOGGING_LEVEL:DEBUG}
  file:
    name: log/cfis.log
  pattern:
    file: '%d{yyyy-MM-dd_HH:mm:ss.SSS} [%thread %-5level %logger{75}] %msg%n'
    console: '%d{yyyy-MM-dd_HH:mm:ss.SSS} [%thread %-5level %logger{75}] %msg%n'
  logback:
    rollingpolicy:
      file-name-pattern: 'log/archived/cfis.%d{yyyy-MM-dd}.%i.log'
      max-file-size: 10MB
      max-history: 100

app:
  category-file-root: ${CFIS_CFR:C:/Users/Alex/Desktop/CFIS_TEST}
  category-file-name: ${CFIS_CFN:.cfis-categories}
  user-access-file-name: ${CFIS_UAFN:.cfis-user-access-file}
  user-session-expiration-timeout: ${CFIS_USET:600000}
  default-user-login: ${CFIS_DEF_USR:admin}
  default-user-password: ${CFIS_DEF_PWD:qawsed}
