# httpOnly: if true then browser script won't be able to access the cookie
# secure: if true then the cookie will be sent only over HTTPS connection
server:
  servlet:
    session:
      timeout: 15m
      cookie:
        http-only: true
        secure: false

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # see: https://jdbc.postgresql.org/documentation/ssl/
  datasource.url: jdbc:postgresql://localhost:5432/cfis?ApplicationName=cfis&ssl=true&sslmode=disable&client_encoding=UTF8
  datasource.driver-class-name: org.postgresql.Driver
  datasource.username: cfis_user
  datasource.password: cfis_password

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:category_file_info_service_changelog.xml
    default-schema: public

logging:
  level:
    root: DEBUG
    org.numamo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  file:
    name: log/cfis.log
  pattern:
    file: '%d{yyyy-MM-dd_HH:mm:ss.SSS} [%thread %-5level %logger{75}] %msg%n'
    console: '%d{yyyy-MM-dd_HH:mm:ss.SSS} [%thread %-5level %logger{75}] %msg%n'
  logback:
    rollingpolicy:
      file-name-pattern: 'log/archived/cfis.%d{yyyy-MM-dd}.%i.log'
      max-file-size: 50MB
      max-history: 60

app:
  category-file-root: C:/Users/Alex/Desktop/CFIS_TEST
  category-file-name: .cfis-categories
  user-access-file-name: .cfis-user-access-file
  user-session-expiration-timeout: 600000